### ISSUE TITLE
Is config flexible enough to allow for different reader classes?

### ISSUE THREAD

**Issue by markus-hinsche** [kbressem/trainlib#10]
I would like to specify

```yaml
transforms:
  prob: 0.1
  mode: [bilinear, nearest]
  base:
    LoadImaged:
      reader: [ITKReader, NrrdReader]
```

but NrrdReader is not interpreted/imported correctly in transforms.py
